services:
  - type: web
    name: attendance-bot-api
    dockerfilePath: Dockerfile
    plan: free
    healthCheckPath: /api/scrape-status
    startCommand: node server.js

cronJobs:
  - name: daily-attendance-check
    schedule: "30 17 * * *"
    dockerfilePath: Dockerfile
    command: curl -X POST https://attendance-bot-api.onrender.com/api/automate
