services:
  - type: web
    name: attendance-bot-api
    # REMOVED: The conflicting 'env: node' line
    dockerfilePath: Dockerfile # <-- Tells Render to use Docker build system
    plan: free
    healthCheckPath: /
    startCommand: node server.js
